Repository hifis-net/ansible-role-rsd, pull requests merged in 2022-06, with the labels that each got.

#36 Make container registry configurable
  README.md
  defaults/main.yml
  templates/docker-compose.yml.j2
Labels: enhancement

#41 Change package management tool named in CONTRIBUTING guide
  CONTRIBUTING.md
Labels: documentation

#31 Add nginx configuration to enable HTTPS by default
  README.md
  defaults/main.yml
  molecule/default/dhparam.pem
  molecule/default/dhparam.pem.license
  molecule/default/molecule.yml
  molecule/default/prepare.yml
  tasks/check.yml
  tasks/install.yml
  templates/docker-compose.yml.j2
  templates/nginx.conf.j2
  templates/rsd-secrets.env.j2
Labels: enhancement

#45 Update template files
  README.md
  defaults/main.yml
  templates/docker-compose.yml.j2
  templates/rsd-secrets.env.j2
Labels: enhancement

#48 Ignore errors during initials dry-run
  tasks/check.yml
Labels: bug
